package com.iflytek.astron.workflow.engine.domain;

import com.iflytek.astron.workflow.engine.constants.NodeExecStatusEnum;
import com.iflytek.astron.workflow.engine.domain.callbacks.GenerateUsage;
import com.iflytek.astron.workflow.exception.NodeCustomException;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;

/**
 * Result of node execution in the workflow engine.
 * <p>
 * This class contains all the information about a node's execution result,
 * including outputs, error information, token usage, and other metadata.
 * 
 * @author 二哥编程星球&Java进阶之路（沉默王二&一灰）
 * @version 1.0.0
 */
@Data
public class NodeRunResult {
    /**
     * Input data passed to the node.
     */
    private Map<String, Object> inputs = new HashMap<>();

    /**
     * Output data produced by the node.
     */
    private Map<String, Object> outputs = new HashMap<>();

    /**
     * Error outputs produced by the node.
     */
    private Map<String, Object> errorOutputs = new HashMap<>();

    /**
     * Raw output from the node execution.
     */
    private String rawOutput = "";

    /**
     * Answer content generated by the node.
     */
    private String nodeAnswerContent = "";

    /**
     * Reasoning content generated by the node.
     */
    private String nodeAnswerReasoningContent = "";

    /**
     * Token cost information for the node execution.
     */
    private GenerateUsage tokenCost = new GenerateUsage();

    /**
     * Error information if the node execution failed.
     */
    private NodeCustomException error = null;

    /**
     * Status of the node execution.
     */
    private NodeExecStatusEnum status;
}